# golangci-lint configuration for StricklySoft Core SDK
# See: https://golangci-lint.run/usage/configuration/
# Using v1.x format for stability. Upgrade to v2 format when ready.
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - copyloopvar

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    # Exclude fmt.Fprint* from errcheck as ignoring return values
    # in fmt.Formatter implementations is standard Go practice
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/StricklySoft/stricklysoft-core
  misspell:
    locale: US
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
    - path: internal/testutil/
      linters:
        - revive
