# GoReleaser Configuration for StricklySoft Core SDK
# See: https://goreleaser.com/customization/
#
# This SDK is a Go library (no binaries). Release automation:
# - Generates checksums for go.mod verification
# - Creates changelog from conventional commits
# - Publishes draft GitHub releases for review
#
# Release Process:
# 1. Create and push a semver tag: git tag v1.0.0 && git push origin v1.0.0
# 2. GitHub Actions triggers release workflow
# 3. Draft release created for review
# 4. Maintainer publishes after verification
#
# Versioning: Follow SemVer (https://semver.org/)
# - Major: Breaking changes
# - Minor: New features (backwards compatible)
# - Patch: Bug fixes (backwards compatible)

version: 2

project_name: stricklysoft-core

# Pre-release hooks
before:
  hooks:
    # Ensure dependencies are tidy
    - go mod tidy
    # Run code generation if needed
    - go generate ./...

# Build configuration
# Skip builds - this is a library, not a binary
builds:
  - skip: true

# Archive configuration (for source tarball if needed)
archives:
  - id: source
    # Format configuration moved to formats (archives.format is deprecated)
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Additional files to include in archive
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/*

# Checksum configuration - REQUIRED for verification
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  # Include extra files in checksum
  extra_files: []

# Changelog configuration with grouping by commit type
changelog:
  # Sort commits by timestamp
  sort: asc
  # Note: 'use: conventional' is a GoReleaser Pro feature and is not
  # available in the OSS distribution. The OSS version relies on
  # regex-based commit grouping (configured in the 'groups' section below)
  # and filter patterns to achieve conventional commit categorization.
  # Commit message filters
  filters:
    # Exclude these commit types from changelog
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"
      - "^refactor:"
      - "Merge pull request"
      - "Merge branch"
  # Group commits by type for organized release notes
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔒 Security"
      regexp: '^.*?sec(urity)?(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "⚡ Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "💥 Breaking Changes"
      regexp: '^.*?!:.+$'
      order: 4
    - title: "📦 Dependencies"
      regexp: '^.*?(deps|dep)(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: "🔧 Other Changes"
      order: 999

# GitHub Release configuration
release:
  github:
    owner: StricklySoft
    name: stricklysoft-core
  # Create draft releases for review before publishing
  draft: true
  # Auto-detect prerelease from tag (e.g., v1.0.0-alpha.1)
  prerelease: auto
  # Release title template
  name_template: "{{ .Tag }}"
  # Release notes header
  header: |
    ## StricklySoft Core SDK {{ .Tag }}

    Welcome to {{ .Tag }} of the StricklySoft Core SDK!

    ### Installation

    ```bash
    go get github.com/StricklySoft/stricklysoft-core@{{ .Tag }}
    ```

    ### Verification

    Verify checksums:
    ```bash
    sha256sum -c checksums.txt
    ```

  # Release notes footer
  footer: |
    ---

    **Full Changelog**: https://github.com/StricklySoft/stricklysoft-core/compare/{{ .PreviousTag }}...{{ .Tag }}

    🤖 This release was automatically generated by [GoReleaser](https://goreleaser.com/).

  # Extra files to upload to the release
  extra_files: []

  # Make latest only for stable releases (not prereleases)
  make_latest: true

  # Replace existing draft releases
  replace_existing_draft: true

  # Skip uploading artifacts for library releases
  skip_upload: false

# Announce configuration (disabled for now)
# announce:
#   skip: true

# Snapshot configuration for testing
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

# Git configuration
git:
  # Ignore lightweight tags
  ignore_tags:
    - "nightly"
    - "latest"
  # Tag sort order
  tag_sort: -version:refname
