version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - skip: true  # SDK library, no binaries to build

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: StricklySoft
    name: stricklysoft-core
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
