// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/StricklySoft/stricklysoft-core/pkg/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: ctx, token
func (_m *MockTokenValidator) Validate(ctx context.Context, token string) (auth.Identity, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 auth.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (auth.Identity, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) auth.Identity); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenValidator_Expecter) Validate(ctx interface{}, token interface{}) *MockTokenValidator_Validate_Call {
	return &MockTokenValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *MockTokenValidator_Validate_Call) Run(run func(ctx context.Context, token string)) *MockTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenValidator_Validate_Call) Return(_a0 auth.Identity, _a1 error) *MockTokenValidator_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenValidator_Validate_Call) RunAndReturn(run func(context.Context, string) (auth.Identity, error)) *MockTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
