// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	lifecycle "github.com/StricklySoft/stricklysoft-core/pkg/lifecycle"
	mock "github.com/stretchr/testify/mock"
)

// MockAgent is an autogenerated mock type for the Agent type
type MockAgent struct {
	mock.Mock
}

type MockAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgent) EXPECT() *MockAgent_Expecter {
	return &MockAgent_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function with given fields:
func (_m *MockAgent) Capabilities() []lifecycle.Capability {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 []lifecycle.Capability
	if rf, ok := ret.Get(0).(func() []lifecycle.Capability); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lifecycle.Capability)
		}
	}

	return r0
}

// MockAgent_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockAgent_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Capabilities() *MockAgent_Capabilities_Call {
	return &MockAgent_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MockAgent_Capabilities_Call) Run(run func()) *MockAgent_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Capabilities_Call) Return(_a0 []lifecycle.Capability) *MockAgent_Capabilities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Capabilities_Call) RunAndReturn(run func() []lifecycle.Capability) *MockAgent_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields: ctx
func (_m *MockAgent) Health(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgent_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockAgent_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Health(ctx interface{}) *MockAgent_Health_Call {
	return &MockAgent_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockAgent_Health_Call) Run(run func(ctx context.Context)) *MockAgent_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAgent_Health_Call) Return(_a0 error) *MockAgent_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Health_Call) RunAndReturn(run func(context.Context) error) *MockAgent_Health_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with given fields:
func (_m *MockAgent) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAgent_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAgent_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAgent_Expecter) ID() *MockAgent_ID_Call {
	return &MockAgent_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAgent_ID_Call) Run(run func()) *MockAgent_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_ID_Call) Return(_a0 string) *MockAgent_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_ID_Call) RunAndReturn(run func() string) *MockAgent_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields:
func (_m *MockAgent) Info() lifecycle.AgentInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 lifecycle.AgentInfo
	if rf, ok := ret.Get(0).(func() lifecycle.AgentInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(lifecycle.AgentInfo)
	}

	return r0
}

// MockAgent_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockAgent_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Info() *MockAgent_Info_Call {
	return &MockAgent_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockAgent_Info_Call) Run(run func()) *MockAgent_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Info_Call) Return(_a0 lifecycle.AgentInfo) *MockAgent_Info_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Info_Call) RunAndReturn(run func() lifecycle.AgentInfo) *MockAgent_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *MockAgent) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAgent_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockAgent_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Name() *MockAgent_Name_Call {
	return &MockAgent_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockAgent_Name_Call) Run(run func()) *MockAgent_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Name_Call) Return(_a0 string) *MockAgent_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Name_Call) RunAndReturn(run func() string) *MockAgent_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function with given fields: ctx
func (_m *MockAgent) Pause(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgent_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockAgent_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Pause(ctx interface{}) *MockAgent_Pause_Call {
	return &MockAgent_Pause_Call{Call: _e.mock.On("Pause", ctx)}
}

func (_c *MockAgent_Pause_Call) Run(run func(ctx context.Context)) *MockAgent_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAgent_Pause_Call) Return(_a0 error) *MockAgent_Pause_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Pause_Call) RunAndReturn(run func(context.Context) error) *MockAgent_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function with given fields: ctx
func (_m *MockAgent) Resume(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgent_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockAgent_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Resume(ctx interface{}) *MockAgent_Resume_Call {
	return &MockAgent_Resume_Call{Call: _e.mock.On("Resume", ctx)}
}

func (_c *MockAgent_Resume_Call) Run(run func(ctx context.Context)) *MockAgent_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAgent_Resume_Call) Return(_a0 error) *MockAgent_Resume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Resume_Call) RunAndReturn(run func(context.Context) error) *MockAgent_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockAgent) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgent_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockAgent_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Start(ctx interface{}) *MockAgent_Start_Call {
	return &MockAgent_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockAgent_Start_Call) Run(run func(ctx context.Context)) *MockAgent_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAgent_Start_Call) Return(_a0 error) *MockAgent_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Start_Call) RunAndReturn(run func(context.Context) error) *MockAgent_Start_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with given fields:
func (_m *MockAgent) State() lifecycle.State {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 lifecycle.State
	if rf, ok := ret.Get(0).(func() lifecycle.State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(lifecycle.State)
	}

	return r0
}

// MockAgent_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockAgent_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockAgent_Expecter) State() *MockAgent_State_Call {
	return &MockAgent_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockAgent_State_Call) Run(run func()) *MockAgent_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_State_Call) Return(_a0 lifecycle.State) *MockAgent_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_State_Call) RunAndReturn(run func() lifecycle.State) *MockAgent_State_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx
func (_m *MockAgent) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgent_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockAgent_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Stop(ctx interface{}) *MockAgent_Stop_Call {
	return &MockAgent_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockAgent_Stop_Call) Run(run func(ctx context.Context)) *MockAgent_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAgent_Stop_Call) Return(_a0 error) *MockAgent_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Stop_Call) RunAndReturn(run func(context.Context) error) *MockAgent_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with given fields:
func (_m *MockAgent) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAgent_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockAgent_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Version() *MockAgent_Version_Call {
	return &MockAgent_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockAgent_Version_Call) Run(run func()) *MockAgent_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Version_Call) Return(_a0 string) *MockAgent_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgent_Version_Call) RunAndReturn(run func() string) *MockAgent_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgent creates a new instance of MockAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgent {
	mock := &MockAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
