// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	auth "github.com/StricklySoft/stricklysoft-core/pkg/auth"
	mock "github.com/stretchr/testify/mock"
)

// MockIdentity is an autogenerated mock type for the Identity type
type MockIdentity struct {
	mock.Mock
}

type MockIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentity) EXPECT() *MockIdentity_Expecter {
	return &MockIdentity_Expecter{mock: &_m.Mock}
}

// Claims provides a mock function with given fields:
func (_m *MockIdentity) Claims() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Claims")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockIdentity_Claims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claims'
type MockIdentity_Claims_Call struct {
	*mock.Call
}

// Claims is a helper method to define mock.On call
func (_e *MockIdentity_Expecter) Claims() *MockIdentity_Claims_Call {
	return &MockIdentity_Claims_Call{Call: _e.mock.On("Claims")}
}

func (_c *MockIdentity_Claims_Call) Run(run func()) *MockIdentity_Claims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentity_Claims_Call) Return(_a0 map[string]interface{}) *MockIdentity_Claims_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdentity_Claims_Call) RunAndReturn(run func() map[string]interface{}) *MockIdentity_Claims_Call {
	_c.Call.Return(run)
	return _c
}

// HasPermission provides a mock function with given fields: resource, action
func (_m *MockIdentity) HasPermission(resource string, action string) bool {
	ret := _m.Called(resource, action)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(resource, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIdentity_HasPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPermission'
type MockIdentity_HasPermission_Call struct {
	*mock.Call
}

// HasPermission is a helper method to define mock.On call
//   - resource string
//   - action string
func (_e *MockIdentity_Expecter) HasPermission(resource interface{}, action interface{}) *MockIdentity_HasPermission_Call {
	return &MockIdentity_HasPermission_Call{Call: _e.mock.On("HasPermission", resource, action)}
}

func (_c *MockIdentity_HasPermission_Call) Run(run func(resource string, action string)) *MockIdentity_HasPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIdentity_HasPermission_Call) Return(_a0 bool) *MockIdentity_HasPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdentity_HasPermission_Call) RunAndReturn(run func(string, string) bool) *MockIdentity_HasPermission_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with given fields:
func (_m *MockIdentity) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIdentity_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIdentity_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIdentity_Expecter) ID() *MockIdentity_ID_Call {
	return &MockIdentity_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIdentity_ID_Call) Run(run func()) *MockIdentity_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentity_ID_Call) Return(_a0 string) *MockIdentity_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdentity_ID_Call) RunAndReturn(run func() string) *MockIdentity_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with given fields:
func (_m *MockIdentity) Type() auth.IdentityType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 auth.IdentityType
	if rf, ok := ret.Get(0).(func() auth.IdentityType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(auth.IdentityType)
	}

	return r0
}

// MockIdentity_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockIdentity_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockIdentity_Expecter) Type() *MockIdentity_Type_Call {
	return &MockIdentity_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockIdentity_Type_Call) Run(run func()) *MockIdentity_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentity_Type_Call) Return(_a0 auth.IdentityType) *MockIdentity_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdentity_Type_Call) RunAndReturn(run func() auth.IdentityType) *MockIdentity_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentity creates a new instance of MockIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentity {
	mock := &MockIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
